LoadModule dav_svn_module modules/mod_dav_svn.so
LoadModule authz_svn_module modules/mod_authz_svn.so

<Location /svn>
  DAV svn
  SVNParentPath /home/svn
  SVNListParentPath On

  # Anonymous read, authenticated write.
  <LimitExcept GET PROPFIND OPTIONS REPORT>
    AuthType Basic
    AuthName "Test Subversion Repository. user=test, password=test"
    AuthUserFile /etc/subversion/passwd
    Require valid-user
  </LimitExcept>
</Location>
